### ISSUE TITLE
Setup is very buggy

### ISSUE THREAD

**Issue by AlternateDev** [2JJ1/Pow-Forum#3]
The setup for Pow Forum is very buggy, if an improper input is passed it will simply just exit without telling what the issue is, even after completing everything it fails to run. Additionally, it doesn't appear to save configuration from running the setup script, and the forum is basically unusable without modifying the source yourself.

Information I've entered:

Domain: localhost (I've also tried inputting an actual domain it'd be running off using Replit)
Support Email: support@<domain>.com
Mailgun Domain: sandbox<id>.mailgun.org
Mailgun API Key: <API Key, I'm hiding this for obvious reasons>
Noreply Email: noreply@<domain>.com

I am then presented with the message "Initial setup complete. Please log into an admin account and continue configuration in the dashboard."

After which, I run "node server.js" and get "Missing support email address. Please run 'npm run setup'".
When running cli.js, the setup is restarted indicating it never gets saved.

Before asking, I've installed all required packages and done everything listed on the GitHub repo.

**Comment by 2JJ1** [comment]
The failure of notice for improper input isn't a bug. There simply is no handling for it. I'll improve the user convenience later on because I know it is easy to make a mistake. Such as repetitively asking for input when it's incorrectly entered.

**Comment by 2JJ1** [comment]
#c00e760

The CLI now repetitively asks for input if it is incorrectly answered. I've also corrected the error reporting for `>npm run setup`.
Albeit, I never was able to replicate your exact issue. It worked fine for me before, but I made changes using guess work. Let me know if it's still not working for you. 

Just use `> git pull origin` to pull the updates. No additional configuration is required

**Comment by AlternateDev** [comment]
It's still quite buggy, try running off of Replit and you'll see what I mean. It should help you iron out a lot of errors too.

(also can we bring back test_bot2 yet :cry:)

**Comment by 2JJ1** [comment]
That explains your issue. It seems Replit doesn't allow the creation and use of .env files, which is critical to this project. This project is not designed to be deployed in limited environments. Even if you could create .env files, you wouldn't get far since you can't install MongoDB locally, which is required as mentioned in the prerequisites.
